#!/bin/bash
python3 -c "
import sys
counts = {}
f = open(sys.argv[1])
f.readline()
for line in f:
    host = line.split('\t')[0]
    counts[host] = counts.get(host, 0) + 1
for host in sorted(counts, key=counts.get, reverse=True)[:11]:
    print(host)
" "$1"
