#!/usr/bin/env bash
# This script loops 1 to 10, displays bad luck 4th, good luck 8th, Best School others
i=0
while [ $i -lt 10 ]
do 
i=$((i+1))
if [ $i -eq 4 ] 
then 
echo "bad luck"
elif [ $i -eq 8 ]
then 
echo "good luck"
else 
echo "Best School"
fi
done 
