#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using kill

# Find the PID of the script and store it in a variable
PID=$(pgrep -f 4-to_infinity_and_beyond)

# Use kill to stop the process
if [ -n "$PID" ]; then
    kill "$PID"
fi
