#!/usr/bin/env bash
# Script qui affiche "To infinity and beyond" et intercepte SIGTERM

# On définit la fonction de capture
trap 'echo "I am invincible!!!"; exit' SIGTERM

# Boucle infinie
while true; do
    echo "To infinity and beyond"
    sleep 2
done
